
SELECT * FROM T_USER;

SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE UPDATE_USER1
    (
    P_ID IN T_USER.ID%TYPE
    , P_POINT IN T_USER.POINT%TYPE
     )
    
IS
BEGIN
    UPDATE T_USER
    SET POINT = P_POINT
    WHERE ID = P_ID;
END ;
/

EXECUTE UPDATE_USER1('test123' , 12323);

----

CREATE OR REPLACE PROCEDURE SELECT_USER1
    (P_GENDER IN T_USER.GENDER%TYPE
    ,P_POINT IN T_USER.POINT%TYPE)
IS
    TYPE ID_TABLE IS TABLE OF T_USER.ID%TYPE
    INDEX BY BINARY_INTEGER;
    
    TYPE NICKNAME_TABLE IS TABLE OF T_USER.NICKNAME%TYPE
    INDEX BY BINARY_INTEGER;
    
    TYPE POINT_TABLE IS TABLE OF T_USER.POINT%TYPE
    INDEX BY BINARY_INTEGER;
    
    ID_ARR ID_TABLE;
    NICKNAME_ARR NICKNAME_TABLE;
    POINT_ARR POINT_TABLE;
    
    i BINARY_INTEGER := 0;
    
BEGIN
    FOR USER_LIST IN (
                        SELECT ID , NICKNAME , POINT
                        FROM T_USER
                        WHERE GENDER = P_GENDER AND POINT > P_POINT
                     ) LOOP
    i := i + 1;
    
    ID_ARR(i) := USER_LIST.ID;
    NICKNAME_ARR(i) := USER_LIST.NICKNAME;
    POINT_ARR(i) := USER_LIST.POINT;
    
    END LOOP;
    
    FOR CNT IN 1..i LOOP
        DBMS_OUTPUT.PUT_LINE('아이디 : ' || ID_ARR(CNT));
        DBMS_OUTPUT.PUT_LINE('닉네임 : ' || NICKNAME_ARR(CNT));
        DBMS_OUTPUT.PUT_LINE('포인트 : ' || POINT_ARR(CNT));
        DBMS_OUTPUT.PUT_LINE('==========================');
        
    END LOOP;

END ;
/

EXECUTE SELECT_USER1('M' , 500);

UPDATE T_USER
SET POINT = 1000;
