SELECT * FROM T_BOARD ;
SELECT * FROM T_BOARDCOMMENT ;
SELECT * FROM T_BOARDFILE ;

SELECT * FROM T_PRODUCT ;
SELECT * FROM T_ORDER ;
SELECT * FROM T_PMANAGE ;
SELECT * FROM T_REVIEW ;

INSERT INTO "SYSTEM"."T_PIMAGE" (P_ID, IMG_NAME, IMG_ORGNAME, IMG_PATH, IMG_SIZE, THUMBNAILYN) VALUES ('ab123', '20230330605.jpg', 'bear.jpg', 'my document', '10', 'N');

INSERT INTO "SYSTEM"."T_PIMAGE" (P_ID, IMG_NAME, IMG_ORGNAME, IMG_PATH, IMG_SIZE, THUMBNAILYN) VALUES ('ab123', '20230330606.jpg', 'king_bear.jpg', 'my document', '10', 'Y');

SELECT * FROM T_PIMAGE ;

SELECT *
FROM T_PRODUCT P
INNER JOIN T_PIMAGE I ON P.P_ID = I.P_ID
WHERE THUMBNAILYN = 'Y';
